local-phone-apps = AccessControl \
                   ActiveApplicationWidget-common-release \
                   AdvSoundDetector \
                   AirWakeUp \
                   AllShareCastPlayer \
                   AllshareFileShare \
                   AllshareFileShareClient \
                   AllshareFileShareServer \
                   AllshareMediaServer \
                   AllshareMediaShare \
                   AntHalService \
                   ANTPlusPlugins \
                   ANTRadioService \
                   ApplicationPermissions \
                   AssistantMenu2 \
                   AutoRunChecker \
                   BadgeProvider \
                   BasicDreams \
                   BCService \
                   BeaconManager \
                   BeamService \
                   BlackScreen \
                   Bluetooth \
                   BluetoothTest \
                   Bridge \
                   CapabilityManagerService \
                   CertInstaller \
                   ChinaHolidayProvider \
                   ChineseClassic2 \
                   ChromecastFrameworkService \
                   ChromeCustomizations \
                   ClipboardSaveService \
                   ClipboardUIService \
                   ClockPackage \
                   CMAWeatherPhone2014 \
                   ColorBlind \
                   ColoredPaper \
                   com.qualcomm.location \
                   com.qualcomm.qti.services.secureui \
                   CoverService \
                   CuVasChecker \
                   DigitalClock \
                   DigitalClockEasy \
                   DigitalPenService \
                   DocumentsUI \
                   Dreamy \
                   DriveLink \
                   DriveLinkRemote \
                   DualCityWidget \
                   DualClockDigital \
                   EasymodeContactsWidget \
                   EasyOneHand2 \
                   EasySettings \
                   EasySidePanel \
                   EdmSimPinService \
                   EdmVpnServices \
                   ELMAgent \
                   EmergencyLauncher \
                   EmergencyModeService \
                   EmergencyProvider \
                   EventNotificationPhase2 \
                   Facebook \
                   FactoryCamera_FB \
                   FBAppManager \
                   FBInstagram_stub \
                   FBMessenger_stub \
                   FBPagesManager_stub \
                   FestivalManager \
                   FestivalMemoryWidget \
                   FestivalSAWidget \
                   FestivalWallpaperPicker \
                   FilterInstaller \
                   FilterManager \
                   FilterProvider \
                   FixmoISA \
                   FlashAnnotate \
                   FlashAnnotateSvc \
                   FlipboardBriefing \
                   Flipboard_cn_T \
                   FWUpgrade \
                   GearManagerStub \
                   GeoLookout \
                   GestureService \
                   GifMaker_T \
                   GreetingCard \
                   GreetingCardWidget \
                   InCallUI \
                   InteractiveTutorial \
                   InterfacePermissions \
                   Kaiti \
                   KeyChain \
                   KeyguardWallpaperUpdator \
                   KNOXAgent \
                   KnoxAttestationAgent \
                   KnoxSetupWizardClient \
                   LocalFOTA \
                   LocateContactsOnMap \
                   MDMApp \
                   MediaConverter_Trim \
                   Miao \
                   minimode-res \
                   MirrorLink \
                   MobilePrint4 \
                   MobilePrintSvc_CUPS \
                   MobilePrintSvc_CUPS_Backend \
                   MobilePrintSvc_Epson \
                   MobilePrintSvc_HP \
                   MobilePrintSvc_Samsung \
                   MobileTrackerEngineTwo \
                   MultiWindowTrayService \
                   Natural2 \
                   Netease \
                   NfcNci \
                   OCRSeg \
                   OCRService \
                   PackageInstaller \
                   PacProcessor \
                   PageBuddyNotiSvc2 \
                   Panorama360Viewer_T \
                   Personalization \
                   PhotoTable \
                   PopupuiReceiver \
                   PowerSharing \
                   Preconfig \
                   PreloadInstaller \
                   QComQMIPermissions \
                   QQInterceptService \
                   QQInterceptUpdate \
                   QuickConnect \
                   QuickConnectInteraction \
                   RCPComponents \
                   RemotePlayer \
                   ResourceManager \
                   ringtoneBR \
                   RootPA \
                   SafetyInformation \
                   SamsungAppsWidget_BannerStyle_common \
                   SamsungCamera3 \
                   SamsungCameraFilter \
                   SamsungChineseIME \
                   SamsungChineseIMEThemeLight \
                   SamsungContentsAgent \
                   SamsungDrmProvider \
                   SamsungMusicRemoteController \
                   SamsungTTS \
                   SapaAudioConnectionService \
                   SapaMonitor \
                   SBrowser \
                   SBrowserTry \
                   SCONE_Android_ProxyService_NoPersistent \
                   SCParser \
                   SearchBoxBaidu_OPEN_V2 \
                   SecDict \
                   SecEmail_K \
                   SecExchange \
                   SecFactoryPhoneTest \
                   SecHTMLViewer \
                   SecSetupWizard2013 \
                   SecTelephonyProviderCherry \
                   SecThemeChooser2 \
                   SecurityManagerService \
                   SecurityProviderSEC \
                   SecVideo \
                   SecVideoPlayer \
                   secvisualeffect-res \
                   SetDefaultLauncher \
                   SettingSearchProvider \
                   ShaoNv \
                   SharingAccessibilitySettings \
                   ShootingModeProvider \
                   SilentLog \
                   SLocation \
                   SmartcardManager \
                   SmartcardService \
                   SmartClipService \
                   SNote4Preload \
                   SPenKeeper \
                   SPenSdk3 \
                   SPlanner \
                   SPlannerWidget \
                   SPrintSpooler2 \
                   Stk2 \
                   Stk \
                   SysScope \
                   TapandpayWidget \
                   TaskManager \
                   TasksProvider \
                   TcpdumpService \
                   TetheringAutomation \
                   TimeService \
                   TravelService \
                   UniversalMDMClient \
                   USBSettings \
                   UserDictionaryProvider \
                   VideoEditor_Lite_T \
                   WeatherDaemon2014 \
                   WebManual \
                   WfdBroker \
                   WhatsApp \
                   WlanTest \
                   Wluc \
                   WritingBuddyService \
                   YahooLiveWeather \
                   YellowPage

local-phone-priv-apps = 3DTourViewer_WQHD_lightTheme \
                        AirMessage \
                        AirMessageProxy \
                        AutomationTest_FB \
                        AutoPreconfig \
                        BackupRestoreConfirmation \
                        CloudAgent_CHN \
                        ContextProvider \
                        CSC \
                        DCMProvider \
                        DefaultContainerService \
                        DeviceKeystring \
                        DeviceTest \
                        DiagMonAgent \
                        DirectShareManager \
                        DocumentService \
                        DSMLawmo \
                        EasyLauncher2 \
                        ExternalStorageProvider \
                        FBInstaller \
                        FingerprintService \
                        FmmDM \
                        FmmDS \
                        FotaClient \
                        FusedLocation \
                        GalaxyApps_3xh \
                        GlobalNetworkLocation_Baidu \
                        HancomOfficeViewer \
                        HealthService \
                        Hearingdro_KK_L \
                        HwModuleTest \
                        InputDevices \
                        intelligenceservice_1.1 \
                        Keyguard \
                        Kies \
                        KLMSAgent \
                        LogsProvider \
                        MagicShot_WQHD_T \
                        MtpApplication \
                        MusicCommonUtility \
                        NoiseField \
                        OmaCP \
                        OneTimeInitializer \
                        OutOfFocusViewer_WQHD_K \
                        PayWithPaypal \
                        PCWClientS18 \
                        PersonalPageService \
                        PhaseBeam \
                        PhoneErrService \
                        PhotoStudio_WQHD_K \
                        Pinboard \
                        ProxyHandler \
                        RNB \
                        RNBShell \
                        SamsungBilling \
                        SamsungLinkPlatform \
                        SamsungMagnifier \
                        SamsungMusic_20 \
                        Samsungservice2_xxhdpi_RTL \
                        SBrowserProviderProxy_PRELOAD \
                        sCloudBackupApp \
                        sCloudDataRelay \
                        sCloudDataSync \
                        sCloudQuotaApp \
                        sCloudSyncCalendar \
                        sCloudSyncContacts \
                        sCloudSyncMemo \
                        sCloudSyncSBrowser \
                        SecCalendarProvider \
                        SecContacts_Note_CHN \
                        SecContactsProvider \
                        SecDownloadProvider \
                        SecEmbeddedServerService \
                        SecGallery2014 \
                        SecLiveWallpapersPicker \
                        SecMediaProvider \
                        SecMms_Cherry \
                        SecMyFiles2014 \
                        SecSafetyAssurance \
                        SecSettings \
                        SecSettingsProvider \
                        SecTeleService \
                        serviceModeApp_FB \
                        ServiceModeApp_RIL \
                        SFinder \
                        SharedStorageBackup \
                        SHealth3_5 \
                        Shell \
                        SKMSAgent \
                        SlidingGallery \
                        SmartAssistant \
                        SmartSelfShot \
                        SOAgent \
                        SoundAlive_20 \
                        SPDClient \
                        SPPPushClient_Prod \
                        SStudio_WQHD_K \
                        S-Voice_Android_phone \
                        SyncmlDM \
                        SystemUI \
                        Tag \
                        TouchWizHome \
                        TrimApp_phone_light_rotation \
                        VpnDialogs \
                        VRSetupWizardStub \
                        WallpaperCropper \
                        WallpaperPicker \
                        WifiConnectionHandler \
                        wssyncmlnps